
/*******************************************************************************
* generated by lcd-image-converter rev.fuck from ass
* image
* filename: Z:/Windows 10 VM/programmable-load/icons/MainBadgeVExt.xml
* name: MainBadgeVExt
*
* preset name: Grayscale 4
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Grayscale, not_used not_used
* split to rows: yes
* bits per pixel: 4
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

#include <stdint.h>
#include <etl/array.h>

#include "Gfx/Icon.h"


// Storage and visibility attributes for bitmap data 
#define BITMAP_STORAGE __attribute__((section(".gfxdata.bitmap")))\
    __attribute__((visibility("hidden")))

///////////////////////////////////////////////////////////////////////////////////////////////////
// Bitmap data
///////////////////////////////////////////////////////////////////////////////////////////////////

//-----------------------
// Size: 16 x 16
// ░▓▓▓▓▓▓▓▓▓▓▓▓▓▓░
    // ▓∙∙∙∙∙∙∙∙∙∙∙∙∙∙▓
    // ▓∙∙∙∙∙█∙∙∙█∙∙∙∙▓
    // ▓∙∙∙∙∙█∙∙∙█∙∙∙∙▓
    // ▓∙∙∙∙∙∙█∙█∙∙∙∙∙▓
    // ▓∙∙∙∙∙∙█∙█∙∙∙∙∙▓
    // ▓∙∙∙∙∙∙█∙█∙∙∙∙∙▓
    // ▓∙∙∙∙∙∙∙█∙∙∙∙∙∙▓
    // ▓∙∙∙∙∙∙∙∙∙∙∙∙∙∙▓
    // ▓∙███∙∙█∙█∙███∙▓
    // ▓∙█∙∙∙∙█∙█∙∙█∙∙▓
    // ▓∙███∙∙∙█∙∙∙█∙∙▓
    // ▓∙█∙∙∙∙█∙█∙∙█∙∙▓
    // ▓∙███∙∙█∙█∙∙█∙∙▓
    // ▓∙∙∙∙∙∙∙∙∙∙∙∙∙∙▓
    // ░▓▓▓▓▓▓▓▓▓▓▓▓▓▓░
//-----------------------
static const etl::array<const uint8_t, 128> image_data_MainBadgeVExt BITMAP_STORAGE{{
    0x4a, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xa4, 
    0xa0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0a, 
    0xa0, 0x00, 0x00, 0xe0, 0x00, 0xe0, 0x00, 0x0a, 
    0xa0, 0x00, 0x00, 0xe0, 0x00, 0xe0, 0x00, 0x0a, 
    0xa0, 0x00, 0x00, 0x2e, 0x0e, 0x20, 0x00, 0x0a, 
    0xa0, 0x00, 0x00, 0x0e, 0x0e, 0x00, 0x00, 0x0a, 
    0xa0, 0x00, 0x00, 0x0e, 0x2e, 0x00, 0x00, 0x0a, 
    0xa0, 0x00, 0x00, 0x02, 0xe2, 0x00, 0x00, 0x0a, 
    0xa0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0a, 
    0xa0, 0xee, 0xe0, 0x0e, 0x0e, 0x0e, 0xee, 0x0a, 
    0xa0, 0xe0, 0x00, 0x0e, 0x1e, 0x00, 0xe0, 0x0a, 
    0xa0, 0xee, 0xe0, 0x01, 0xe1, 0x00, 0xe0, 0x0a, 
    0xa0, 0xe0, 0x00, 0x0e, 0x1e, 0x00, 0xe0, 0x0a, 
    0xa0, 0xee, 0xe0, 0x0e, 0x0e, 0x00, 0xe0, 0x0a, 
    0xa0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0a, 
    0x4a, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xa4
}};

///////////////////////////////////////////////////////////////////////////////////////////////////
// Icon object definition
///////////////////////////////////////////////////////////////////////////////////////////////////
const Gfx::Icon Gfx::Icon::gMainBadgeVExt{
    .size = {16, 16},
    .bitmap = image_data_MainBadgeVExt,
};


